import type { Metadata } from "next";
import { Inter,Roboto_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";



const inter = Inter({ subsets: ["latin"] });
const robotoMono = Roboto_Mono({ subsets: ["latin"],
  variable:"--robotoMono",
  weight:["100","200","300","400","500","600","700"]
 });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={robotoMono.variable}>{children}</body>
    </html>
  );
}
